name: Deploy GitHub Pages

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install "cython<3.0.0" wheel
          pip install setuptools
          pip install "pyyaml==5.4.1" --no-build-isolation
          pip install openapi2jsonschema

      - name: Build files
        run: bash build.sh

      - name: Build site
        run: |
          cp ./index.html ./output/
          cp ./kubernetes_logo.png ./output/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './output'

  deploy:
    needs: build

    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
